from .llm import prompt_ollama

develop_prompt = """HƯỚNG DẪN
Bạn được cung cấp 1 bản ghi. Dựa vào bản ghi, hãy kiểm tra Claim đã có đủ bằng chứng để chứng minh chưa như sau:
Kiểm tra các khía cạnh của Claim đã được nhắc đến trong các phần summary chưa.
- Nếu chưa đủ bằng chứng để chứng minh Claim, in ra từ khóa tìm kiếm web cụ thể để thu thập thêm bằng chứng. In ra từ khóa tìm kiếm dưới dạng: TÌM KIẾM: <từ khóa tìm kiếm>. Lưu ý không in từ khóa tìm kiếm đã được nhắc đến trong web_search("..")
- Nếu đã có đủ bằng chứng để chứng minh Claim, in ra duy nhất "NONE".

BẢN GHI:
{record}

In ra kết quả của bạn:
"""

def develop(record, think=True):
    """
    Develops an analysis of the claim using the provided record.

    Args:
        record (str): The record containing evidence for the analysis.
        think (bool): Whether to use chain-of-thought (default True)
    Returns:
        str: The analysis generated by the LLM.
    """
    prompt = develop_prompt.format(record=record)
    return prompt_ollama(prompt, think=think, use_reasoning_model=True)