from .llm import prompt_ollama

develop_prompt = """
Hướng dẫn
Bạn vừa thu thập được Bằng chứng mới. Hãy phân tích tính đúng/sai của Phát biểu dựa trên bằng chứng và tuân thủ các quy tắc sau:
- Tập trung phát triển insight mới. Không lặp lại dài dòng nội dung từ Record. Không nhắc lại nguyên văn Claim.
- Viết suy luận theo từng bước; khi cần có thể giải thích chi tiết.
- Tùy độ phức tạp, viết khoảng 1–3 đoạn; càng ngắn gọn càng tốt.
- Nếu thông tin chưa đủ để kết luận, nêu rõ dữ liệu nào còn thiếu.
- Nếu trích nguồn web, dẫn link bằng Markdown (dùng URL gốc làm hyperlink).
- Chỉ dùng thông tin có trong các bằng chứng đã ghi nhận; có thể dùng kiến thức thường thức ở mức hợp lý.

Nếu thực sự cần thu thập thêm bằng chứng, bạn có thể đề xuất các hành động. Nếu không cần, chỉ đưa ra phần suy luận, không thêm gì khác.
Tuân thủ:
- Các hành động hợp lệ nằm trong phần Valid Actions (kèm mô tả ngắn). Không có hành động nào khác ngoài danh sách này.
- Mỗi hành động phải theo đúng định dạng chỉ định ở Valid Actions.
- Đề xuất ít nhưng đủ; không lặp lại hay trùng với các hành động đã có.
- Đặt toàn bộ các hành động trong một khối mã (Markdown code block) duy nhất ở cuối câu trả lời.

Lưu ý kỹ thuật: Giữ nguyên cú pháp chính xác khi in ra hành động, ví dụ web_search("...") và token NONE (không dịch).

Valid Actions:
geolocate: Xác định quốc gia nơi ảnh được chụp bằng ID ảnh.
reverse search: Tìm kiếm ảnh ngược trên web để tìm ảnh tương tự.
web search: Tìm kiếm web mở cho các trang liên quan.
image search: Tìm hình ảnh liên quan cho một truy vấn.
NONE: Không đề xuất hành động nào.

Ví dụ:
geolocate(<image:k>)
reverse_search(<image:k>)
web_search("New Zealand Food Bill 2020")
image_search("China officials white suits carry people")
NONE

Record:
{record}
Your Analysis:
"""

def develop(record, think=True):
    """
    Develops an analysis of the claim using the provided record.

    Args:
        record (str): The record containing evidence for the analysis.
        think (bool): Whether to use chain-of-thought (default True)
    Returns:
        str: The analysis generated by the LLM.
    """
    prompt = develop_prompt.format(record=record)
    return prompt_ollama(prompt, think=think)